# http server for palaisdetokyo.eu
server {
    server_name palaisdetokyo.eu www.palaisdetokyo.eu;

    listen 8080;
    root /app;
    index index.html;

    # restrict allowed methods
    if ($request_method !~ ^(GET|HEAD)$) {
        return 405;
    }

    error_page 404 /404.html;

    # security headers for marmotte.love
    add_header X-Frame-Options DENY;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy "default-src 'self';
                                        style-src 'self' 'unsafe-inline' fonts.googleapis.com;
                                        font-src 'self' fonts.gstatic.com;
                                        script-src 'self' 'unsafe-inline' www.google.com;
                                        frame-src 'self' www.google.com;";
    add_header Strict-Transport-Security "max-age=31536100; includeSubDomains; preload";

    # redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
    include common.conf;
}
